# Generated by Django 2.2.7 on 2019-11-30 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_name', models.CharField(max_length=256)),
                ('transcribed_file_name', models.CharField(max_length=256)),
                ('upload_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
