# Generated by Django 2.1.3 on 2018-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.FloatField()),
                ('magnitude', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='File',
            new_name='AudioFile',
        ),
    ]
