# Generated by Django 2.1.3 on 2018-11-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0002_auto_20181123_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanalysis',
            name='method',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
