# Generated by Django 2.2.7 on 2019-11-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_analysis', '0003_textanalysis_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='TextAnalysis',
        ),
    ]
