# Generated by Django 2.2.7 on 2019-11-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcription_analysis', '0004_auto_20191119_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_name', models.CharField(max_length=256)),
                ('audio_file_path', models.CharField(max_length=256)),
                ('transcribed_file_name', models.CharField(max_length=256)),
                ('transcribed_file_path', models.CharField(max_length=256)),
                ('upload_date', models.DateField()),
            ],
        ),
    ]
