# Generated by Django 2.2.7 on 2019-11-20 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_analysis', '0005_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
